const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1120}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4340');
 await page.waitForFunction(()=>document.querySelector('#appsCount').textContent==='6');
 await page.locator('#capture').click();
 await page.waitForFunction(()=>!document.querySelector('#apply').disabled);
 await page.locator('#apply').click();
 await page.waitForFunction(()=>document.querySelector('#phase').textContent==='faults observed');
 assert.equal(await page.locator('#faultCount').textContent(),'17');
 await page.screenshot({path:'.browser-test/disaster.png',fullPage:true});
 await page.locator('#reset').click();
 await page.waitForFunction(()=>document.querySelector('#phase').textContent==='normal');
 assert.equal(await page.locator('#readyCount').textContent(),'19');
 await page.locator('[data-kind=partial]').click();
 await page.locator('#count').fill('999');
 await page.locator('#apply').click();
 await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('exceeds'));
 await page.locator('#count').fill('2');
 await page.locator('#apply').click();
 await page.waitForFunction(()=>document.querySelector('#faultCount').textContent==='2');
 await page.locator('#reset').click();
 await page.waitForFunction(()=>document.querySelector('#phase').textContent==='normal');
 await page.locator('[data-kind=single]').click();
 await page.locator('#apply').click();
 await page.waitForFunction(()=>document.querySelector('#faultCount').textContent==='1');
 await page.locator('#reset').click();
 await page.waitForFunction(()=>document.querySelector('#phase').textContent==='normal');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'.browser-test/mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow');
 assert.deepEqual(errors,[]);
 const security=await page.evaluate(async()=>{const r=await fetch('/api/apply',{method:'POST',body:'{}'});return r.status});
 assert.equal(security,403);
 console.log('Browser passed: disaster, partial, single pod, reset, visible error, CSRF, mobile layout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
